### PR TITLE
Camera Plugin Issues Fixed

### PR DESCRIPTION
**Pull request by vmwsree**
- Resolution issue on different phones
- Crash on Multiple click on camera
- Auto Focus Disabled for better response.(User will not initiate scan unless document is in focus), avoids unnecessary delay.
- Shutter Sound
 - Give any feed back if u want to remove any other changes

### CODE REVIEW

**Comment by UlanNurmatov** [comment]
**Hello. I get this right after starting the debugging:**

Launching lib/main.dart on SM J120H in debug mode...
E/AndroidRuntime(28293): FATAL EXCEPTION: main
E/AndroidRuntime(28293): Process: com.ulan.world_time_app, PID: 28293
E/AndroidRuntime(28293): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(28293): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime(28293): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(28293): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28293): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28293): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(28293): 	... 1 more
E/AndroidRuntime(28293): Caused by: android.hardware.camera2.CameraAccessException: Illegal state encountered in camera service.
E/AndroidRuntime(28293): 	at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:131)
E/AndroidRuntime(28293): 	at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
E/AndroidRuntime(28293): 	at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
E/AndroidRuntime(28293): 	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
E/AndroidRuntime(28293): 	at $Proxy0.getCameraCharacteristics(Unknown Source)
E/AndroidRuntime(28293): 	at android.hardware.camera2.CameraManager.getOrCreateDeviceIdListLocked(CameraManager.java:479)
E/AndroidRuntime(28293): 	at android.hardware.camera2.CameraManager.getCameraIdList(CameraManager.java:100)
E/AndroidRuntime(28293): 	at com.sample.edgedetection.scan.ScanPresenter.getBackFacingCameraId(ScanPresenter.kt:116)
E/AndroidRuntime(28293): 	at com.sample.edgedetection.scan.ScanPresenter.initCamera(ScanPresenter.kt:138)
E/AndroidRuntime(28293): 	at com.sample.edgedetection.scan.ScanPresenter.surfaceCreated(ScanPresenter.kt:202)
E/AndroidRuntime(28293): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:714)
E/AndroidRuntime(28293): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:208)
E/AndroidRuntime(28293): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
E/AndroidRuntime(28293): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2327)
E/AndroidRuntime(28293): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
E/AndroidRuntime(28293): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
E/AndroidRuntime(28293): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
E/AndroidRuntime(28293): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
E/AndroidRuntime(28293): 	at android.view.Choreographer.doFrame(Choreographer.java:576)
E/AndroidRuntime(28293): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
E/AndroidRuntime(28293): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(28293): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28293): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(28293): 	at android.app.ActivityThread.main(ActivityThread.java:6917)
E/AndroidRuntime(28293): 	... 4 more
E/AndroidRuntime(28783): FATAL EXCEPTION: main
E/AndroidRuntime(28783): Process: com.ulan.world_time_app, PID: 28783
E/AndroidRuntime(28783): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(28783): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime(28783): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(28783): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28783): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28783): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(28783): 	... 1 more
E/AndroidRuntime(28783): Caused by: android.hardware.camera2.CameraAccessException: Illegal state encountered in camera service.
E/AndroidRuntime(28783): 	at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:131)
E/AndroidRuntime(28783): 	at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
E/AndroidRuntime(28783): 	at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
E/AndroidRuntime(28783): 	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
E/AndroidRuntime(28783): 	at $Proxy0.getCameraCharacteristics(Unknown Source)
E/AndroidRuntime(28783): 	at android.hardware.camera2.CameraManager.getOrCreateDeviceIdListLocked(CameraManager.java:479)
E/AndroidRuntime(28783): 	at android.hardware.camera2.CameraManager.getCameraIdList(CameraManager.java:100)
E/AndroidRuntime(28783): 	at com.sample.edgedetection.scan.ScanPresenter.getBackFacingCameraId(ScanPresenter.kt:116)
E/AndroidRuntime(28783): 	at com.sample.edgedetection.scan.ScanPresenter.initCamera(ScanPresenter.kt:138)
E/AndroidRuntime(28783): 	at com.sample.edgedetection.scan.ScanPresenter.surfaceCreated(ScanPresenter.kt:202)
E/AndroidRuntime(28783): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:714)
E/AndroidRuntime(28783): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:208)
E/AndroidRuntime(28783): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
E/AndroidRuntime(28783): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2327)
E/AndroidRuntime(28783): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
E/AndroidRuntime(28783): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
E/AndroidRuntime(28783): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
E/AndroidRuntime(28783): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
E/AndroidRuntime(28783): 	at android.view.Choreographer.doFrame(Choreographer.java:576)
E/AndroidRuntime(28783): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
E/AndroidRuntime(28783): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(28783): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28783): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(28783): 	at android.app.ActivityThread.main(ActivityThread.java:6917)
E/AndroidRuntime(28783): 	... 4 more
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:53114/nZ51yy6WGYA=/ws

**And this when opening the camera. And the app crashes.**

I/Timeline(29074): Timeline: Activity_idle id: android.os.BinderProxy@5645db0 time:30111987
D/ViewRootImpl(29074): ViewPostImeInputStage ACTION_DOWN
D/ViewRootImpl(29074): ViewPostImeInputStage ACTION_DOWN
D/ViewRootImpl(29074): ViewPostImeInputStage ACTION_DOWN
I/Timeline(29074): Timeline: Activity_launch_request id:com.ulan.world_time_app time:30127388
W/ResourcesManager(29074): getTopLevelResources: /data/app/com.ulan.world_time_app-1/base.apk / 1.0 running in com.ulan.world_time_app rsrc of package null
W/ResourcesManager(29074): getTopLevelResources: /data/app/com.ulan.world_time_app-1/base.apk / 1.0 running in com.ulan.world_time_app rsrc of package null
W/ResourcesManager(29074): getTopLevelResources: /data/app/com.ulan.world_time_app-1/base.apk / 1.0 running in com.ulan.world_time_app rsrc of package null
W/art     (29074): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/PhoneWindow(29074): *FMB* installDecor mIsFloating : false
D/PhoneWindow(29074): *FMB* installDecor flags : -2139029248
I/art     (29074): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
I/art     (29074): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
D/TextView(29074): setTypeface with style : 0
D/TextView(29074): setTypeface with style : 0
D/OpenCV/StaticHelper(29074): Trying to get library list
E/OpenCV/StaticHelper(29074): OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper(29074): Library list: ""
D/OpenCV/StaticHelper(29074): First attempt to load libs
D/OpenCV/StaticHelper(29074): Trying to init OpenCV libs
D/OpenCV/StaticHelper(29074): Trying to load library opencv_java3
I/OpenCV  (29074): calling android_getCpuFeatures() ...
I/OpenCV  (29074): calling android_getCpuFeatures() ... Done (7ff)
D/OpenCV/StaticHelper(29074): Library opencv_java3 loaded
D/OpenCV/StaticHelper(29074): First attempt to load libs is OK
I/OpenCV/StaticHelper(29074): General configuration for OpenCV 3.3.0 =====================================
I/OpenCV/StaticHelper(29074):   Version control:               3.3.0
I/OpenCV/StaticHelper(29074):   Platform:
I/OpenCV/StaticHelper(29074):     Timestamp:                   2017-08-04T00:30:10Z
I/OpenCV/StaticHelper(29074):     Host:                        Linux 4.8.0-58-generic x86_64
I/OpenCV/StaticHelper(29074):     Target:                      Linux 1 armv7-a
I/OpenCV/StaticHelper(29074):     CMake:                       2.8.12.2
I/OpenCV/StaticHelper(29074):     CMake generator:             Ninja
I/OpenCV/StaticHelper(29074):     CMake build tool:            /usr/bin/ninja
I/OpenCV/StaticHelper(29074):     Configuration:               Release
I/OpenCV/StaticHelper(29074):   CPU/HW features:
I/OpenCV/StaticHelper(29074):     Baseline:                    NEON NEON
I/OpenCV/StaticHelper(29074):       requested:                 DETECT
I/OpenCV/StaticHelper(29074):       required:                  NEON
I/OpenCV/StaticHelper(29074):       disabled:                  VFPV3
I/OpenCV/StaticHelper(29074):   C/C++:
I/OpenCV/StaticHelper(29074):     Built as dynamic libs?:      NO
I/OpenCV/StaticHelper(29074):     C++ Compiler:                /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ (ver 4.8)
I/OpenCV/StaticHelper(29074):     C++ flags (Release):         -fexceptions -frtti -fpic -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-9/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer  -mfpu=neon -mfp16-format=ieee -fvisibility=hidden -fvisibility-inlines-hidden -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -DNDEBUG
I/OpenCV/StaticHelper(29074):     C++ flags (Debug):           -fexceptions -frtti -fpic -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-9/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer  -mfpu=neon -mfp16-format=ieee -fvisibility=hidden -fvisibility-inlines-hidden -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
I/OpenCV/StaticHelper(29074):     C Compiler:                  /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
I/OpenCV/StaticHelper(29074):     C flags (Release):           -fexceptions -fpic -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-9/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer  -mfpu=neon -mfp16-format=ieee -fvisibility=hidden -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -DNDEBUG
I/OpenCV/StaticHelper(29074):     C flags (Debug):             -fexceptions -fpic -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-9/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer  -mfpu=neon -mfp16-format=ieee -fvisibility=hidden -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
I/OpenCV/StaticHelper(29074):     Linker flags (Release):      -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now
I/OpenCV/StaticHelper(29074):     Linker flags (Debug):        -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now
I/OpenCV/StaticHelper(29074):     ccache:                      YES
I/OpenCV/StaticHelper(29074):     Precompiled headers:         NO
I/OpenCV/StaticHelper(29074):     Extra dependencies:          z dl m log
I/OpenCV/StaticHelper(29074):     3rdparty dependencies:       cpufeatures libprotobuf libjpeg libwebp libpng libtiff libjasper IlmImf tegra_hal tbb
I/OpenCV/StaticHelper(29074):   OpenCV modules:
I/OpenCV/StaticHelper(29074):     To be built:                 core flann imgproc ml objdetect photo video dnn imgcodecs shape videoio highgui superres ts features2d calib3d java stitching videostab
I/OpenCV/StaticHelper(29074):     Disabled:                    world
I/OpenCV/StaticHelper(29074):     Disabled by dependency:      -
I/OpenCV/StaticHelper(29074):     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev python2 python3 viz
I/OpenCV/StaticHelper(29074):   Android:
I/OpenCV/StaticHelper(29074):     Android ABI:                 armeabi-v7a with NEON
I/OpenCV/StaticHelper(29074):     STL type:                    gnustl_static
I/OpenCV/StaticHelper(29074):     Native API level:            android-9
I/OpenCV/StaticHelper(29074):     SDK target:                  android-11
I/OpenCV/StaticHelper(29074):     Android NDK:                 /opt/android/android-ndk-r10e (toolchain: arm-linux-androideabi-4.8)
I/OpenCV/StaticHelper(29074):     android tool:                /opt/android/android-sdk-java7/tools/android (Android SDK Tools, revision 25.2.2.)
I/OpenCV/StaticHelper(29074):     Google Play manager:         NO
I/OpenCV/StaticHelper(29074):     Android examples:            YES
I/OpenCV/StaticHelper(29074):   GUI:
I/OpenCV/StaticHelper(29074):     GTK+:                        NO
I/OpenCV/StaticHelper(29074):     GThread :                    NO
I/OpenCV/StaticHelper(29074):     GtkGlExt:                    NO
I/OpenCV/StaticHelper(29074):     OpenGL support:              NO
I/OpenCV/StaticHelper(29074):     VTK support:                 NO
I/OpenCV/StaticHelper(29074):   Media I/O:
I/OpenCV/StaticHelper(29074):     ZLib:                        z (ver 1.2.3)
I/OpenCV/StaticHelper(29074):     JPEG:                        build (ver 90)
I/OpenCV/StaticHelper(29074):     WEBP:                        build (ver encoder: 0x020e)
I/OpenCV/StaticHelper(29074):     PNG:                         build (ver 1.6.24)
I/OpenCV/StaticHelper(29074):     TIFF:                        build (ver 42 - 4.0.2)
I/OpenCV/StaticHelper(29074):     JPEG 2000:                   build (ver 1.900.1)
I/OpenCV/StaticHelper(29074):     OpenEXR:                     build (ver 1.7.1)
I/OpenCV/StaticHelper(29074):     GDAL:                        NO
I/OpenCV/StaticHelper(29074):     GDCM:                        NO
I/OpenCV/StaticHelper(29074):   Video I/O:
I/OpenCV/StaticHelper(29074):   Parallel framework:            TBB (ver 4.4 interface 9003)
I/OpenCV/StaticHelper(29074):   Trace:                         YES ()
I/OpenCV/StaticHelper(29074):   Other third-party libraries:
I/OpenCV/StaticHelper(29074):     Use Intel IPP:               NO
I/OpenCV/StaticHelper(29074):     Use Intel IPP IW:            NO
I/OpenCV/StaticHelper(29074):     Use Eigen:                   NO
I/OpenCV/StaticHelper(29074):     Use Cuda:                    NO
I/OpenCV/StaticHelper(29074):     Use OpenCL:                  NO
I/OpenCV/StaticHelper(29074):     Use OpenVX:                  NO
I/OpenCV/StaticHelper(29074):     Use custom HAL:              YES (carotene (ver 0.0.1))
I/OpenCV/StaticHelper(29074):   Python 2:
I/OpenCV/StaticHelper(29074):     Interpreter:                 /usr/bin/python2.7 (ver 2.7.6)
I/OpenCV/StaticHelper(29074):   Python 3:
I/OpenCV/StaticHelper(29074):     Interpreter:                 /usr/bin/python3.4 (ver 3.4.3)
I/OpenCV/StaticHelper(29074):   Python (for build):            /usr/bin/python2.7
I/OpenCV/StaticHelper(29074):   Java:
I/OpenCV/StaticHelper(29074):     ant:                         /usr/bin/ant (ver 1.9.3)
I/OpenCV/StaticHelper(29074):     Java wrappers:               YES
I/OpenCV/StaticHelper(29074):     Java tests:                  YES
I/OpenCV/StaticHelper(29074):   Matlab:                        NO
I/OpenCV/StaticHelper(29074):   Tests and samples:
I/OpenCV/StaticHelper(29074):     Tests:                       YES
I/OpenCV/StaticHelper(29074):     Performance tests:           NO
I/OpenCV/StaticHelper(29074):     C/C++ Examples:              NO
I/OpenCV/StaticHelper(29074):   Install path:                  /build/master_pack-android/build/o4a/install
I/OpenCV/StaticHelper(29074):   cvconfig.h is in:              /build/master_pack-android/build/o4a
I/OpenCV/StaticHelper(29074): -----------------------------------------------------------------
I/ScanPresenter(29074): camera null
D/PhoneWindow(29074): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
D/PhoneWindow(29074): *FMB* isFloatingMenuEnabled return false
I/CameraManagerGlobal(29074): getCameraService: Reconnecting to camera service
D/AndroidRuntime(29074): Shutting down VM
E/AndroidRuntime(29074): FATAL EXCEPTION: main
E/AndroidRuntime(29074): Process: com.ulan.world_time_app, PID: 29074
E/AndroidRuntime(29074): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(29074): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime(29074): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(29074): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29074): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(29074): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(29074): 	... 1 more
E/AndroidRuntime(29074): Caused by: android.hardware.camera2.CameraAccessException: Illegal state encountered in camera service.
E/AndroidRuntime(29074): 	at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:131)
E/AndroidRuntime(29074): 	at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
E/AndroidRuntime(29074): 	at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
E/AndroidRuntime(29074): 	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
E/AndroidRuntime(29074): 	at $Proxy0.getCameraCharacteristics(Unknown Source)
E/AndroidRuntime(29074): 	at android.hardware.camera2.CameraManager.getOrCreateDeviceIdListLocked(CameraManager.java:479)
E/AndroidRuntime(29074): 	at android.hardware.camera2.CameraManager.getCameraIdList(CameraManager.java:100)
E/AndroidRuntime(29074): 	at com.sample.edgedetection.scan.ScanPresenter.getBackFacingCameraId(ScanPresenter.kt:116)
E/AndroidRuntime(29074): 	at com.sample.edgedetection.scan.ScanPresenter.initCamera(ScanPresenter.kt:138)
E/AndroidRuntime(29074): 	at com.sample.edgedetection.scan.ScanPresenter.surfaceCreated(ScanPresenter.kt:202)
E/AndroidRuntime(29074): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:714)
E/AndroidRuntime(29074): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:208)
E/AndroidRuntime(29074): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
E/AndroidRuntime(29074): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2327)
E/AndroidRuntime(29074): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
E/AndroidRuntime(29074): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
E/AndroidRuntime(29074): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
E/AndroidRuntime(29074): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
E/AndroidRuntime(29074): 	at android.view.Choreographer.doFrame(Choreographer.java:576)
E/AndroidRuntime(29074): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
E/AndroidRuntime(29074): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(29074): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(29074): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(29074): 	at android.app.ActivityThread.main(ActivityThread.java:6917)
E/AndroidRuntime(29074): 	... 4 more
Lost connection to device.
Exited (sigterm)

**Comment by sawankumarbundelkhandi** [comment]
@vmwsree thanks for PR. I will test it and merge if everything is working.

**Comment by sawankumarbundelkhandi** [comment]
@vmwsree will you be able to resolve the conflicts? Let me know if you can't I will.

**Comment by Faisalkc4u** [comment]
Hi, Am also facing the same error. Is there any updates on this merge

**Comment by sawankumarbundelkhandi** [comment]
@vmwsree I have merged your PR.

@Faisalkc4u  I will release it in soon over pub.

**Pull request merged**
