### PR TITLE
Contrast, Rotation, Dark Theme, Shape Recognition Improvement

### PR DESCRIPTION
**Pull request by tiagosito**
Added contrast with black and white colors, dark theme, image reset for the initial stage, rotate image with 90º angles, save black and white and rotated image, improved image recognition so that no triangle appears all the time.

### CODE REVIEW

**Comment by sawankumarbundelkhandi** [comment]
@tiagosito Thanks for the PR. I will check it soon.

**Comment by tiagosito** [comment]
> @tiagosito Thanks for the PR. I will check it soon.

Ok, I'm awaiting!

**Comment by Muzammil-Bilwani** [comment]
Any update on that?

**Comment by monolidth** [comment]
Since this project is inactive, I decided to maintain the project at: https://github.com/ReceiptManager/edge_detection
and I merged your PR.

**Comment by monolidth** [comment]
Update, I integrate your work in my application. It is really awesome!

**Comment by sawankumarbundelkhandi** [comment]
@tiagosito thanks for this amazing PR. I have merged it. Now the plugin will support Rotate, Black, and White Filter on both OS.

**Comment by tiagosito** [comment]
> @tiagosito thanks for this amazing PR. I have merged it. Now the plugin will support Rotate, Black, and White Filter on both OS.

Cool, really cool that you enjoyed the PR 👍

**Pull request merged**
