### PR TITLE
Updated to AndroidX libraries.

### PR DESCRIPTION
**Pull request by BugsBunnyBR**

### CODE REVIEW

**Comment by firatcetiner** [comment]
Thanks for your contribution. I have tried this a while ago but couldn't manage to fully adopt both libraries and the code to AndroidX.

**Comment by BugsBunnyBR** [comment]
If it fails to run share the logcat stacktrace and I will take a look.

**Comment by firatcetiner** [comment]
Volia! It's working and I think it's ready for merge by @sawankumarbundelkhandi , hopefully in the near future. Thanks again!

**Comment by firatcetiner** [comment]
It's working, yet last day I tried installing my app on my phone and saw that using this plugin increased the release APK size by almost 70MB, is it normal?

**Comment by marcos930807** [comment]
> It's working, yet last day I tried installing my app on my phone and saw that using this plugin increased the release APK size by almost 70MB, is it normal?

Yes, becouse jniLibs inside SmartPaperScan Android, for this reason i am not using this plugins

**Comment by sawankumarbundelkhandi** [comment]
@BugsBunnyBR Thanks for the PR.

@marcos930807 You can use abiFilters for reducing the size
https://android.jlelse.eu/controlling-apk-size-when-using-native-libraries-45c6c0e5b70a

**Comment by sawankumarbundelkhandi** [comment]
https://proandroiddev.com/reducing-apk-size-by-using-abi-filters-and-apk-split-74a68a885f4e

**Pull request merged**
