### PR TITLE
Support AGP 8

### PR DESCRIPTION
**Pull request by knottx**
Support AGP 8

### CODE REVIEW

**Comment by rahul260792** [comment]
@knottx any workaround to fix issue for now?

**Comment by sawankumarbundelkhandi** [comment]
@knottx thanks for the PR

**Comment by sawankumarbundelkhandi** [comment]
@knottx I think this change is causing issue while running the app. I am reverting the PR for now.

**Comment by Purvik** [comment]
@sawankumarbundelkhandi First thank you for this amazing plug in however do we have any probable timeline to get support for AGP 8 for this plugin in near future? 
Many of us are expecting that to be available as Google play store also enforce API 34 to be used as compile SDK. I would have upgraded it but lacking native Android area specially in Kotlin. Appreciated again.

**Pull request merged**
